// Generated by CoffeeScript 1.7.1
var DEBUG, GRAVITY, HEIGHT, SPEED, WIDTH, birds, main, tube;

DEBUG = false;

SPEED = 0;

GRAVITY = 0;

HEIGHT = 480;

WIDTH = 287;

tube = null;

birds = null;

main = function() {
  var create, game, preload, state;
  preload = function() {
    var assets;
    assets = {
      image: {
        "bg": 'res/bg.png'
      }
    };
    Object.keys(assets).forEach(function(type) {
      Object.keys(assets[type]).forEach(function(id) {
        game.load[type].apply(game.load, [id].concat(assets[type][id]));
      });
    });
  };
  create = function() {
    game.add.sprite(0, 0, 'bg');
  };
  state = {
    preload: preload,
    create: create
  };
  return game = new Phaser.Game(WIDTH, HEIGHT, Phaser.CANVAS, 'screem', state, false);
};

main();
